### ISSUE TITLE
Web-UI fail to start

### ISSUE THREAD

**Issue by nlarzon** [juliusloman/netxms-dockerfiles#1]
Log file:
INFO: Loaded APR based Apache Tomcat Native library 1.2.10 using APR version 1.5.1.
Feb 24, 2017 2:28:28 PM org.apache.catalina.core.AprLifecycleListener init
INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
Feb 24, 2017 2:28:28 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFO: OpenSSL successfully initialized with version OpenSSL 1.0.2j  26 Sep 2016
Feb 24, 2017 2:28:29 PM org.apache.coyote.http11.Http11AprProtocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Feb 24, 2017 2:28:29 PM org.apache.coyote.ajp.AjpAprProtocol init
INFO: Initializing Coyote AJP/1.3 on ajp-8009
Feb 24, 2017 2:28:29 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 2245 ms
Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardService start
INFO: Starting service Catalina
Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.48
Feb 24, 2017 2:28:29 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive nxmc.war
Feb 24, 2017 2:28:29 PM org.apache.catalina.startup.ContextConfig init
SEVERE: Exception fixing docBase for context [/nxmc] 
java.util.zip.ZipException: error in opening zip file
  at java.util.zip.ZipFile.open(Native Method)
  at java.util.zip.ZipFile.<init>(ZipFile.java:215)
  at java.util.zip.ZipFile.<init>(ZipFile.java:145)
  at java.util.jar.JarFile.<init>(JarFile.java:154)
  at java.util.jar.JarFile.<init>(JarFile.java:91)
  at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
  at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
  at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
  at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
  at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
  at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:149)
  at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:882)
  at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:1009)
  at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:276)
  at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
  at org.apache.catalina.core.StandardContext.init(StandardContext.java:5777)
  at org.apache.catalina.core.StandardContext.start(StandardContext.java:4519)
  at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:803)
  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:780)
  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
  at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:944)
  at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:779)
  at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:505)
  at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1322)
  at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:325)
  at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
  at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1069)
  at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
  at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
  at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
  at org.apache.catalina.core.StandardService.start(StandardService.java:525)
  at org.apache.catalina.core.StandardServer.start(StandardServer.java:761)
  at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
  at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardContext resourcesStart
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Invalid or unreadable WAR file : error in opening zip file
  at org.apache.naming.resources.WARDirContext.setDocBase(WARDirContext.java:135)
  at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4390)
  at org.apache.catalina.core.StandardContext.start(StandardContext.java:4563)
  at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:803)
  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:780)
  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
  at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:944)
  at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:779)
  at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:505)
  at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1322)
  at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:325)
  at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
  at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1069)
  at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
  at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
  at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
  at org.apache.catalina.core.StandardService.start(StandardService.java:525)
  at org.apache.catalina.core.StandardServer.start(StandardServer.java:761)
  at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
  at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardContext start
SEVERE: Error in resourceStart()
Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardContext start
SEVERE: Error getConfigured
Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [/nxmc] startup failed due to previous errors
Feb 24, 2017 2:28:29 PM org.apache.catalina.core.StandardContext stop
INFO: Container org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/nxmc] has not been started
Feb 24, 2017 2:28:29 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory docs
Feb 24, 2017 2:28:30 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory examples
Feb 24, 2017 2:28:32 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory host-manager
Feb 24, 2017 2:28:32 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory manager
Feb 24, 2017 2:28:33 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory ROOT
Feb 24, 2017 2:28:33 PM org.apache.coyote.http11.Http11AprProtocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Feb 24, 2017 2:28:33 PM org.apache.coyote.ajp.AjpAprProtocol start
INFO: Starting Coyote AJP/1.3 on ajp-8009
Feb 24, 2017 2:28:33 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 4353 ms

**Comment by nlarzon** [comment]
Solution:
In file Dockerfile update curl link to have https.
curl http**s**://www.netxms.org/download/webui/nxmc-${VERSION}.war

**Comment by juliusloman** [comment]
Fixed (added -L to follow redirects). Additionally latest stable version has been pushed (2.0.8) including nxmc native console.
